---
apiVersion: v1
kind: Service
metadata:
  name: helloworldwebapp-service
  namespace: helloworldwebapp-prod
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: helloworldwebapp
  type: LoadBalancer
  loadBalancerIP: ""
