apiVersion: v1
kind: Namespace
metadata:
  name: sampleapp-staging

---

apiVersion: v1
kind: Service
metadata:
  name: sampleapp-service
  namespace: sampleapp-staging
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: sampleapp
  type: LoadBalancer
  loadBalancerIP: ""
