---
apiVersion: batch/v1
kind: Job
metadata:
  name: validate-deployment
  namespace: sampleapp-prod
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - command:
            - /bin/sh
            - '-c'
            - curl --max-time 120 sampleapp-service
          image: 'appropriate/curl:latest'
          name: validate-deployment
      restartPolicy: Never
