---
apiVersion: v1
kind: Service
metadata:
  name: helloworldwebapp-service
  namespace: helloworldwebapp-prod
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    frontedBy: helloworldwebapp-prod # will be applied to backends by Spinnaker
  type: LoadBalancer
  loadBalancerIP: ""
